#!/usr/bin/env python
import os, sys

NAO_HOME = os.environ['NAO_HOME'] = '/home/' + os.environ['USER'] + '/nao/trunk'
os.chdir(NAO_HOME + '/install')
os.system('./install_libs')
os.system('./install_naoqi')
os.system('./install_vision')
os.system('./install32bit.sh')
os.system('sudo cp nao.sh /etc/profile.d/')
